### ISSUE TITLE
HON integration not result

### ISSUE THREAD

**Issue by millenniumy2k** [gvigroux/hon#23]
I created the folder in the custom_components “hon”, downloaded the repository via HACS, but the folder remains empty … or inserted the files by copying them from the zip then … but in no case, in “DEICE and SERVICE”, I see the “HON” integration … how can I do?

**Comment by Lemonadel** [comment]
Hello I am also facing similar problem.
Cloned repo, then restarted and only face error when starts adding integration from
Integrations > Add new integration > hon

Did the same with adding repo to HACS and downloading files.
 
Home Assistant 2021.11.3 , their OS. Not
Updated yet due to stupid merge changes made with BLE devices, fans and stability Issues.
Never had problems with other repos.

![B5659809-CC17-4AB2-87ED-99209CD69E34](https://user-images.githubusercontent.com/43881989/194511592-23ea19e6-35b8-48d8-baff-5b018764668b.jpeg)

**Comment by gvigroux** [comment]
> I created the folder in the custom_components “hon”, downloaded the repository via HACS, but the folder remains empty … or inserted the files by copying them from the zip then … but in no case, in “DEICE and SERVICE”, I see the “HON” integration … how can I do?

The "hon" directly must be in your "config/custom_components/"
You can clone the directory and copy the file at the good place. Just restart HA and you will be able to add the hon integration
